### ISSUE TITLE
Build fail on Ubuntu 18.04

### ISSUE THREAD

**Issue by bebetocf** [TIGERs-Mannheim/AutoReferee#2] opened 2019-09-19 18:47 UTC
I'm trying to build the AutoReferee on Ubuntu 18.04, but I getting a error on `common-math 2019-SNAPSHOT` build. Here is the output of running `./build.sh`

```
[INFO] Reactor Summary:
[INFO] 
[INFO] sumatra-parent 2019-SNAPSHOT ....................... SUCCESS [01:07 min]
[INFO] common-math 2019-SNAPSHOT .......................... FAILURE [01:16 min]
[INFO] common 2019-SNAPSHOT ............................... SKIPPED
[INFO] common-bot 2019-SNAPSHOT ........................... SKIPPED
[INFO] sumatra-model 2019-SNAPSHOT ........................ SKIPPED
[INFO] moduli-cam 2019-SNAPSHOT ........................... SKIPPED
[INFO] moduli-geometry 2019-SNAPSHOT ...................... SKIPPED
[INFO] moduli-referee 2019-SNAPSHOT ....................... SKIPPED
[INFO] moduli-record 2019-SNAPSHOT ........................ SKIPPED
[INFO] common-gui 2019-SNAPSHOT ........................... SKIPPED
[INFO] common-gui-config 2019-SNAPSHOT .................... SKIPPED
[INFO] moduli-vision 2019-SNAPSHOT ........................ SKIPPED
[INFO] moduli-wp 2019-SNAPSHOT ............................ SKIPPED
[INFO] moduli-autoreferee 2019-SNAPSHOT ................... SKIPPED
[INFO] moduli-game-controller-protocol 2019-SNAPSHOT ...... SKIPPED
[INFO] sumatra-gui-log 2019-SNAPSHOT ...................... SKIPPED
[INFO] sumatra-gui-visualizer 2019-SNAPSHOT ............... SKIPPED
[INFO] autoreferee-gui 2019-SNAPSHOT ...................... SKIPPED
[INFO] sumatra-snapshot 2019-SNAPSHOT ..................... SKIPPED
[INFO] sumatra-gui-replay 2019-SNAPSHOT ................... SKIPPED
[INFO] sumatra-gui-referee 2019-SNAPSHOT .................. SKIPPED
[INFO] autoreferee-main 2019-SNAPSHOT ..................... SKIPPED
[INFO] Autoreferee 2019 ................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:05 min
[INFO] Finished at: 2019-09-19T15:21:41-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project common-math: Compilation failure: Compilation failure: 
[ERROR] error reading /home/robocin-ssl/Desktop/ssl-autorefs/tigers/repository/com/sleepycat/je/7.5.11/je-7.5.11.jar; zip file is empty
[ERROR] error reading /home/robocin-ssl/Desktop/ssl-autorefs/tigers/repository/com/sleepycat/je/7.5.11/je-7.5.11.jar; zip file is empty
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/Vector2.java:[10,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/AVector2.java:[12,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/AVector.java:[24,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/AVector.java:[32,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/AVector2.java:[25,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/Vector2.java:[25,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/Vector3.java:[9,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/AVector3.java:[9,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/AVector3.java:[20,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/Vector3.java:[24,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/VectorN.java:[11,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/VectorN.java:[21,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/line/v2/ALine.java:[9,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/line/v2/ALine.java:[20,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/Vector2f.java:[7,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/Vector2f.java:[22,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/line/Line.java:[18,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/line/ALine.java:[9,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/line/ALine.java:[21,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/line/Line.java:[32,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/circle/ACircle.java:[9,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/circle/ACircular.java:[5,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/circle/ACircular.java:[15,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/circle/ACircle.java:[21,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/tube/Tube.java:[10,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/tube/Tube.java:[25,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/angle/Rotation.java:[7,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/angle/AAngularMeasure.java:[7,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/angle/AAngularMeasure.java:[15,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/angle/Rotation.java:[21,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/Vector3f.java:[7,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/Vector3f.java:[20,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/circle/Arc.java:[7,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/circle/AArc.java:[7,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/circle/AArc.java:[15,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/circle/Arc.java:[18,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/pose/Pose.java:[12,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/pose/Pose.java:[25,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/triangle/ATriangle.java:[11,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/triangle/ATriangle.java:[20,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/triangle/Triangle.java:[15,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/triangle/Triangle.java:[31,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/circle/Circle.java:[21,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/circle/Circle.java:[33,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/rectangle/ARectangle.java:[20,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/rectangle/ARectangle.java:[36,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/quadrilateral/AQuadrilateral.java:[10,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/quadrilateral/AQuadrilateral.java:[22,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/rectangle/Rectangle.java:[9,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/rectangle/Rectangle.java:[24,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/angle/Angle.java:[7,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/angle/Angle.java:[21,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/ellipse/Ellipse.java:[7,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/ellipse/AEllipse.java:[11,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/ellipse/AEllipse.java:[25,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/ellipse/Ellipse.java:[20,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/quadrilateral/Quadrilateral.java:[20,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/quadrilateral/Quadrilateral.java:[31,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/line/v2/LineSegment.java:[11,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/line/v2/LineSegment.java:[22,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/ValuePoint.java:[10,35] package com.sleepycat.persist.model does not exist
[ERROR] /home/robocin-ssl/Desktop/ssl-autorefs/tigers/modules/common-math/src/main/java/edu/tigers/sumatra/math/vector/ValuePoint.java:[23,2] cannot find symbol
[ERROR]   symbol: class Persistent
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :common-math
```

**Comment by kkimurak** [comment] 2019-09-21 08:54
I thinks the problem is same as #1 .  
I was relieved that somebody had the same problem 
(It means most of everyone got same error, not an  environmental problem).

**Comment by g3force** [comment] 2019-09-21 09:22
yes, that's a duplicate of #1

**Closed as completed by g3force** 2019-09-21 09:22 UTC
